# Generated by Django 3.1.2 on 2020-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCommande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
