# Generated by Django 3.1.2 on 2020-11-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCommande', '0002_auto_20201030_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='archive',
        ),
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(null=True, upload_to='produits'),
        ),
    ]
